import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { PageHeadComponent } from './page-head.component';
import { BadgeComponent } from '../ui/badge.component';
import { IconComponent } from '../ui/icon.component';

const FEATURES = [
  { icon: 'dashboard', title: 'Token & cost visibility', body: 'Every request, every project, all time by default — not capped at 30 days.' },
  { icon: 'wrench', title: 'Tool & skill breakdowns', body: 'See which tools, skills, and MCP servers actually drive usage, per project.' },
  { icon: 'bolt', title: 'Live activity', body: 'A live indicator and event feed reflect what Claude Code is doing right now.' },
  { icon: 'plug', title: 'Full trace inspection', body: 'Open the complete, untruncated prompt and response behind any request.' },
  { icon: 'download', title: 'Report export', body: 'Download usage or project summaries as CSV or JSON for your own analysis.' },
  { icon: 'moon', title: 'Dark & light mode', body: 'Matches your OS preference by default, with a persistent manual toggle.' },
];

/**
 * Port of pages/About.tsx. Text follows JSX whitespace rules exactly: lines of one JSX text run join with a single
 * space; a line break between text and an element is dropped; each {' '} is its own text node (<ng-container>{{ ' ' }}).
 */
@Component({
  selector: 'tt-about',
  standalone: true,
  imports: [RouterLink, PageHeadComponent, BadgeComponent, IconComponent],
  host: { style: 'display: contents' },
  template: `
    <div class="space-y-8 max-w-3xl">
      <div ttPageHead eyebrow="Product" title="About Claude Telemetry Enterprise" subtitle="A local-first observability console for Claude Code — see exactly where your tokens, tool calls, and skills go, without sending any of that data anywhere but your own machine."></div>

      <div class="bg-surface border border-line rounded-lg p-5"><h3 class="text-sm font-bold mb-2.5">What this is, in plain terms</h3><div class="text-sm text-ink-soft leading-relaxed"><p>Claude Telemetry Enterprise is a small program that runs on your own computer, alongside Claude Code. It quietly keeps a record of how Claude Code is being used — how many tokens each request costs, which tools and skills get called, which MCP servers are active, and which project each of those happened in — and shows it back to you in a dashboard you can search, filter, and export.</p><p class="mt-3">Nothing about that record is guessed after the fact from a bill or an invoice: it is built the moment things actually happen, by reading the same files Claude Code already writes for itself. Nothing about it is sent anywhere either — there is no account to sign into and no server to trust besides the one already running on your machine.</p></div></div>

      <div class="bg-surface border border-line rounded-lg p-5"><h3 class="text-sm font-bold mb-2.5">What you can do with it</h3><div class="text-sm text-ink-soft leading-relaxed"><div class="grid grid-cols-1 sm:grid-cols-2 gap-3">@for (f of features; track f.title) {<div class="flex gap-3 bg-surface-muted rounded-lg p-3.5"><svg [ttIcon]="f.icon" class="text-accent shrink-0 mt-0.5" [width]="20" [height]="20"></svg><div><div class="text-ink font-semibold text-sm">{{ f.title }}</div><div class="text-ink-soft text-xs mt-0.5">{{ f.body }}</div></div></div>}</div></div></div>

      <div class="bg-surface border border-line rounded-lg p-5"><h3 class="text-sm font-bold mb-2.5">How it works, without the jargon</h3><div class="text-sm text-ink-soft leading-relaxed"><ol class="space-y-3 list-none"><li class="flex gap-3"><span class="shrink-0 w-6 h-6 rounded-full bg-accent-soft text-accent-strong text-xs font-extrabold grid place-items-center mt-0.5">1</span><div><div class="text-ink font-semibold text-sm mb-0.5">Claude Code tells us when something happens</div><p>Five small hooks (already wired in automatically during install) notify this tool the instant a session starts, a prompt is sent, or a tool runs — so live activity shows up right away, not on a delay.</p></div></li><li class="flex gap-3"><span class="shrink-0 w-6 h-6 rounded-full bg-accent-soft text-accent-strong text-xs font-extrabold grid place-items-center mt-0.5">2</span><div><div class="text-ink font-semibold text-sm mb-0.5">A background process fills in the exact numbers</div><p>Every request's real token usage only exists in Claude Code's own session files, so a background process reads those files on a short timer and fills in the precise counts — catching up automatically on anything it missed if it was off for a while.</p></div></li><li class="flex gap-3"><span class="shrink-0 w-6 h-6 rounded-full bg-accent-soft text-accent-strong text-xs font-extrabold grid place-items-center mt-0.5">3</span><div><div class="text-ink font-semibold text-sm mb-0.5">The dashboard shows you both</div><p>Everything lands in one local database, and this dashboard reads from it — nothing you see here required Claude Code to be told about this tool, or required any data to leave your machine.</p></div></li></ol><p class="mt-3">The technical version of this — the actual database tables and data-flow diagrams — is in<ng-container>{{ ' ' }}</ng-container><a href="https://github.com/sarveshtalele/tokentelemetry/blob/main/docs/ARCHITECTURE.md" target="_blank" rel="noreferrer" class="text-accent-strong hover:underline">docs/ARCHITECTURE.md</a>.</p></div></div>

      <div class="bg-surface border border-line rounded-lg p-5"><h3 class="text-sm font-bold mb-2.5">Exact vs. estimated — what “attributed” means</h3><div class="text-sm text-ink-soft leading-relaxed"><p class="mb-3">The Claude API reports token usage per <em>request</em>, not per file or tool call. So anywhere you see an <span ttBadge tone="success">Exact</span> badge, that number came straight from the API. Anywhere you see an <span ttBadge tone="warning">Estimated</span> badge — attribution hotspots, top files/paths, per-project token breakdowns by category — that number is a heuristic: each request's exact token count is divided across the tool calls active near it in the transcript, then split again across the file paths each of those tools touched.</p><p>A slice that couldn't be matched to any nearby tool call is bucketed as<ng-container>{{ ' ' }}</ng-container><span class="font-mono">[unattributed]</span> rather than silently dropped or guessed. Treat estimated numbers as directionally useful for finding hotspots, not as a precise per-file cost.</p></div></div>

      <div class="bg-surface border border-line rounded-lg p-5"><h3 class="text-sm font-bold mb-2.5">Full prompts and responses</h3><div class="text-sm text-ink-soft leading-relaxed"><p>List views (Requests, Project → Requests) show short truncated previews for speed. Click a row, then “Open full prompt &amp; response” to open the complete, untruncated prompt and response for that request in its own page —<ng-container>{{ ' ' }}</ng-container><a routerLink="/requests" class="text-accent-strong hover:underline">start from Requests</a>.</p></div></div>

      <div class="bg-surface border border-line rounded-lg p-5"><h3 class="text-sm font-bold mb-2.5">Why is “cache read” so much bigger than “input”?</h3><div class="text-sm text-ink-soft leading-relaxed"><p class="mb-3">Claude Code sends your entire conversation on every request (the API is stateless), but most of that — the system prompt, tool definitions, and everything said earlier in the session — is usually a prompt-cache hit by the second turn. The API bills that reused portion as <span class="font-mono">cache read</span>, at a fraction of fresh-token cost, and only counts genuinely new content as<ng-container>{{ ' ' }}</ng-container><span class="font-mono">input</span>. So a request showing <b>Input: 2</b> and<ng-container>{{ ' ' }}</ng-container><b>Cache read: 764,387</b> isn't hiding anything — that 764K really is mostly your system prompt and prior conversation, exact and fully accounted for, just filed under a different label than you might expect.</p><p>One limitation worth naming directly: Claude Code doesn't expose the literal system prompt or tool definition text anywhere this collector can see — not in session transcripts, not in hook payloads. So the<ng-container>{{ ' ' }}</ng-container><a routerLink="/requests" class="text-accent-strong hover:underline">full prompt view</a><ng-container>{{ ' ' }}</ng-container>can show you every user message and tool result that went into a request, but never the system prompt itself. Its exact token cost is still fully captured above — just not its content.</p></div></div>

      <div class="bg-surface border border-line rounded-lg p-5"><h3 class="text-sm font-bold mb-2.5">What's excluded on purpose</h3><div class="text-sm text-ink-soft leading-relaxed"><p>Cost/pricing columns are intentionally left out of the primary UI — billing depends on the plan in effect and isn't a reliable token-telemetry primitive, so it would be misleading to display it alongside exact/estimated token data.</p></div></div>

      <div class="bg-surface border border-line rounded-lg p-5"><h3 class="text-sm font-bold mb-2.5">Local-first and private by design</h3><div class="text-sm text-ink-soft leading-relaxed"><p>Everything runs on your machine: a Python collector + FastAPI backend on top of a local SQLite file, and this React UI talking to it over <span class="font-mono">/api/v1</span> — never a request outside <span class="font-mono">127.0.0.1</span>. See<ng-container>{{ ' ' }}</ng-container><a routerLink="/settings" class="text-accent-strong hover:underline">Settings</a><ng-container>{{ ' ' }}</ng-container>for the exact database path and collector status on this machine.</p><p class="mt-3">The project is open source under the MIT license. The full source, the installation guide, and a complete security review are on<ng-container>{{ ' ' }}</ng-container><a href="https://github.com/sarveshtalele/tokentelemetry" target="_blank" rel="noreferrer" class="text-accent-strong hover:underline">GitHub</a>.</p></div></div>
    </div>
  `,
})
export class AboutComponent {
  readonly features = FEATURES;
}
