// `tokentelemetry shortcut`: a real app launcher with the Token Telemetry
// icon, so it can be pinned like any other app.
//   Linux   -> ~/.local/share/applications/tokentelemetry.desktop (+ Desktop copy)
//   macOS   -> ~/Applications/Token Telemetry.app
//   Windows -> Start Menu + Desktop shortcuts (.lnk)
// Launching runs `tokentelemetry start`, which starts whatever isn't running
// and opens the dashboard. Neither Windows nor macOS lets a program pin
// itself to the taskbar/Dock, so that last step is one right-click (or drag),
// which `shortcut` explains.
const fs = require('fs');
const os = require('os');
const path = require('path');
const { spawnSync } = require('child_process');
const paths = require('./paths');

const APP_NAME = 'Token Telemetry';
const LINUX_ID = 'tokentelemetry';

function iconSource(file) {
  const stable = path.join(paths.installDir(), 'cli', 'assets', file);
  return fs.existsSync(stable) ? stable : path.join(paths.packageRoot(), 'assets', file);
}

function run(cmd, args) {
  return spawnSync(cmd, args, { encoding: 'utf8', windowsHide: true });
}

// ---------- Linux ----------

function desktopQuote(s) {
  // Desktop Entry spec: inside a quoted Exec arg escape \ " ` $; then the
  // string-level escape doubles every backslash again, and a literal % is %%.
  const quoted = `"${String(s).replace(/([\\"`$])/g, '\\$1')}"`;
  return quoted.replace(/\\/g, '\\\\').replace(/%/g, '%%');
}

function linuxDesktopEntry(node = process.execPath, bin = paths.stableBinPath(), icon = LINUX_ID) {
  return `[Desktop Entry]
Type=Application
Version=1.0
Name=${APP_NAME}
GenericName=Claude Code token observability
Comment=See where every Claude Code token goes
Exec=${desktopQuote(node)} ${desktopQuote(bin)} start
Icon=${icon}
Terminal=false
Categories=Development;Utility;Monitor;
Keywords=claude;tokens;telemetry;observability;mcp;
StartupNotify=false
`;
}

function linuxDesktopDir() {
  const res = run('xdg-user-dir', ['DESKTOP']);
  const dir = !res.error && res.status === 0 ? res.stdout.trim() : path.join(os.homedir(), 'Desktop');
  return dir && dir !== os.homedir() && fs.existsSync(dir) ? dir : null;
}

function linuxPaths() {
  const data = process.env.XDG_DATA_HOME || path.join(os.homedir(), '.local', 'share');
  return {
    entry: path.join(data, 'applications', `${LINUX_ID}.desktop`),
    icon: path.join(data, 'icons', 'hicolor', '512x512', 'apps', `${LINUX_ID}.png`),
  };
}

function linuxCreate() {
  const p = linuxPaths();
  fs.mkdirSync(path.dirname(p.icon), { recursive: true });
  fs.copyFileSync(iconSource('icon.png'), p.icon);
  fs.mkdirSync(path.dirname(p.entry), { recursive: true });
  fs.writeFileSync(p.entry, linuxDesktopEntry(process.execPath, paths.stableBinPath(), p.icon), { mode: 0o755 });
  run('update-desktop-database', [path.dirname(p.entry)]);
  const created = [p.entry];
  const desk = linuxDesktopDir();
  if (desk) {
    const target = path.join(desk, `${LINUX_ID}.desktop`);
    fs.copyFileSync(p.entry, target);
    fs.chmodSync(target, 0o755);
    run('gio', ['set', target, 'metadata::trusted', 'true']); // GNOME: allow launching
    created.push(target);
  }
  return {
    created,
    pin: 'Open your app launcher, search "Token Telemetry", then right-click → Add to Favorites / Pin to panel.',
  };
}

function linuxRemove() {
  const p = linuxPaths();
  const desk = linuxDesktopDir();
  const removed = [p.entry, p.icon, desk && path.join(desk, `${LINUX_ID}.desktop`)].filter((f) => f && fs.existsSync(f));
  removed.forEach((f) => fs.rmSync(f, { force: true }));
  return removed;
}

// ---------- macOS ----------

function macAppDir() {
  return path.join(os.homedir(), 'Applications', `${APP_NAME}.app`);
}

function xmlEscape(s) {
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function shQuote(s) {
  return `'${String(s).replace(/'/g, `'\\''`)}'`;
}

function macInfoPlist(version = paths.version()) {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>${APP_NAME}</string>
  <key>CFBundleDisplayName</key><string>${APP_NAME}</string>
  <key>CFBundleIdentifier</key><string>com.tokentelemetry.launcher</string>
  <key>CFBundleVersion</key><string>${version}</string>
  <key>CFBundleShortVersionString</key><string>${version}</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleExecutable</key><string>tokentelemetry</string>
  <key>CFBundleIconFile</key><string>icon</string>
  <key>LSUIElement</key><true/>
  <key>LSMinimumSystemVersion</key><string>10.13</string>
</dict>
</plist>
`;
}

function macLauncherScript(node = process.execPath, bin = paths.stableBinPath(), log = path.join(paths.logDir(), 'launcher.log')) {
  return `#!/bin/sh
# Generated by \`tokentelemetry shortcut\`. Starts anything not running, then opens the dashboard.
mkdir -p ${shQuote(path.dirname(log))}
exec ${shQuote(node)} ${shQuote(bin)} start >> ${shQuote(log)} 2>&1
`;
}

function macCreate({ dock = false } = {}) {
  const app = macAppDir();
  fs.rmSync(app, { recursive: true, force: true });
  fs.mkdirSync(path.join(app, 'Contents', 'MacOS'), { recursive: true });
  fs.mkdirSync(path.join(app, 'Contents', 'Resources'), { recursive: true });
  fs.writeFileSync(path.join(app, 'Contents', 'Info.plist'), macInfoPlist());
  const exe = path.join(app, 'Contents', 'MacOS', 'tokentelemetry');
  fs.writeFileSync(exe, macLauncherScript(), { mode: 0o755 });
  fs.copyFileSync(iconSource('icon.icns'), path.join(app, 'Contents', 'Resources', 'icon.icns'));
  run('touch', [app]); // refresh Finder's icon cache
  if (dock) {
    const tile = `<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>${xmlEscape(`file://${encodeURI(app)}/`)}</string><key>_CFURLStringType</key><integer>15</integer></dict></dict></dict>`;
    run('defaults', ['write', 'com.apple.dock', 'persistent-apps', '-array-add', tile]);
    run('killall', ['Dock']);
  }
  return {
    created: [app],
    pin: dock
      ? 'Added to the Dock.'
      : `Open ~/Applications in Finder and drag "${APP_NAME}" to the Dock (or re-run with --dock).`,
  };
}

function macRemove() {
  const app = macAppDir();
  if (!fs.existsSync(app)) return [];
  fs.rmSync(app, { recursive: true, force: true });
  return [app];
}

// ---------- Windows ----------

function psQuote(s) {
  return `'${String(s).replace(/'/g, "''")}'`;
}

function windowsShortcutScript(node = process.execPath, bin = paths.stableBinPath(), icon = iconSource('icon.ico')) {
  const targets = [
    "[Environment]::GetFolderPath('Programs')",
    "[Environment]::GetFolderPath('Desktop')",
  ];
  return [
    '$shell = New-Object -ComObject WScript.Shell',
    ...targets.map(
      (dir) =>
        `$s = $shell.CreateShortcut((Join-Path ${dir} ${psQuote(`${APP_NAME}.lnk`)})); ` +
        `$s.TargetPath = ${psQuote(node)}; $s.Arguments = ${psQuote(`"${bin}" start`)}; ` +
        `$s.WorkingDirectory = ${psQuote(paths.installDir())}; $s.IconLocation = ${psQuote(`${icon},0`)}; ` +
        `$s.WindowStyle = 7; $s.Description = ${psQuote('See where every Claude Code token goes')}; $s.Save(); ` +
        `Write-Output (Join-Path ${dir} ${psQuote(`${APP_NAME}.lnk`)})`,
    ),
  ].join('\n');
}

function windowsCreate() {
  const res = run('powershell.exe', ['-NoProfile', '-NonInteractive', '-Command', windowsShortcutScript()]);
  if (res.error || res.status !== 0) {
    throw new Error(`Could not create shortcuts: ${res.stderr || res.error?.message || 'unknown error'}`);
  }
  return {
    created: res.stdout.split(/\r?\n/).filter(Boolean),
    pin: `Press the Windows key, type "${APP_NAME}", right-click it → Pin to taskbar (or Pin to Start).`,
  };
}

function windowsRemove() {
  const ps =
    "foreach ($d in @([Environment]::GetFolderPath('Programs'), [Environment]::GetFolderPath('Desktop'))) { " +
    `$f = Join-Path $d ${psQuote(`${APP_NAME}.lnk`)}; if (Test-Path $f) { Remove-Item $f; Write-Output $f } }`;
  const res = run('powershell.exe', ['-NoProfile', '-NonInteractive', '-Command', ps]);
  return res.status === 0 ? res.stdout.split(/\r?\n/).filter(Boolean) : [];
}

// ---------- Dispatch ----------

function create(opts = {}) {
  if (process.platform === 'linux') return linuxCreate();
  if (process.platform === 'darwin') return macCreate(opts);
  if (process.platform === 'win32') return windowsCreate();
  throw new Error(`Shortcuts aren't supported on platform "${process.platform}".`);
}

function remove() {
  if (process.platform === 'linux') return linuxRemove();
  if (process.platform === 'darwin') return macRemove();
  if (process.platform === 'win32') return windowsRemove();
  return [];
}

module.exports = { create, remove, linuxDesktopEntry, macInfoPlist, macLauncherScript, windowsShortcutScript };
